ERROR 2025-07-06 23:12:45,154 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard.html
ERROR 2025-07-07 01:07:57,111 log Internal Server Error: /applications/
Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 880, in _resolve_lookup
    current = current[bit]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 890, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'NoneType' object has no attribute 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 896, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 321, in render
    return nodelist.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 736, in resolve
    arg_vals.append(arg.resolve(context))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/template/base.py", line 903, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [username] in None
ERROR 2025-07-07 01:32:08,232 log Internal Server Error: /accounts/users/
Traceback (most recent call last):
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/views/generic/list.py", line 174, in get
    context = self.get_context_data()
  File "/home/alis/PycharmProjects/crm_project/apps/accounts/views.py", line 114, in get_context_data
    for user in context['users']:
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 84, in pre_sql_setup
    self.setup_query(with_col_aliases=with_col_aliases)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 73, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select(
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 279, in get_select
    related_klass_infos = self.get_related_selections(select, select_mask)
  File "/home/alis/PycharmProjects/crm_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1367, in get_related_selections
    raise FieldError(
django.core.exceptions.FieldError: Invalid field name(s) given in select_related: 'client', 'operator', 'status'. Choices are: created_by
